### ISSUE TITLE
Add a docker registry

### ISSUE THREAD

**Issue by jens-koster** [jens-koster/the-free-data-stack#7]
takes forever to re-build the spark cluster, let's add local docker registry, should speed this up. And make us independent of an external service.
chatgpt suggests using the official docker registry and joxit as a ui on top of it.
[joxit on github](https://github.com/Joxit/docker-registry-ui)

```
 version: '3'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=Local Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
```
