### ISSUE TITLE
add a python package repository

### ISSUE THREAD

**Issue by jens-koster** [jens-koster/the-free-data-stack#8]
Goo dway to get a grip on python packaging and distribution.

chatgpt says to use devpy, I see no reason to doubt that.

```
version: '3'
services:
  devpi:
    image: devpi/devpi-server
    container_name: devpi
    ports:
      - "3141:3141"
    volumes:
      - devpi-data:/data
    command: ["--serverdir", "/data", "--start"]

volumes:
  devpi-data:
```

`docker exec -it devpi devpi-init`

```
devpi use http://localhost:3141
devpi login root --password=''
devpi user -m root password=yourpassword
devpi index -c dev env='dev'

```
This creates:
User: root
Index: dev
Full path: http://localhost:3141/root/dev/

build package

```
pip install build
python -m build
```

upload package
```
devpi use http://localhost:3141/root/dev
devpi login root --password=yourpassword
devpi upload
```
